name: 宣源車體防護 (@x.y.uan)

on:
  push:
    branches: [main]
    paths:
      - 'xuan-yuan/**'
  workflow_dispatch:

jobs:
  upload:
    if: ${{ github.actor == github.repository_owner }}
    runs-on: ubuntu-latest
    environment: 
      name: xuan-yuan
      url: https://line.me/R/ti/p/@x.y.uan
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: 安裝相依套件
      run: yarn
    - name: 上傳圖文選單
      uses: nick-fields/retry@v2
      with:
        timeout_seconds: 600
        max_attempts: 3
        retry_on: error
        command: yarn upload
      env:
        LINEOA_ACCESS_TOKEN: ${{ secrets.LINEOA_ACCESS_TOKEN }}
        RICHMENU_DIRECTORY: xuan-yuan